name: Publish docs via GitHub Pages Manually
on: [workflow_dispatch]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          poetry build
          pkg=`ls dist/hbase*.tar.gz`
          pip install ${pkg}

      - name: Deploy docs
        run: |
          mkdocs gh-deploy --force
